### ISSUE TITLE
ChatGPT-API-Unityのインポート中にエラー

### ISSUE THREAD

**Issue by fumitakayano** [mochi-neko/ChatGPT-API-unity#1]
ChatGPT-API-Unityを公開してくださってありがとうございます。
こちらの環境でもUnity上でもちねこさんの体験を実装してみたいと考えインポートの途上です。

README.mdで記述されたAdd dependencies:が上手く行か無いのですが、ヘルプを頂けないでしょうか？
次の症状です。

---
1) Unity2021.3.18f1でで新規プロジェクトtest_ChatGPT-API-unityを作成
2) ..\test_ChatGPT-API-unity\Packages\manifest.jsonにAdd dependencies:以下のコードを追記して保存
3) プロジェクト起動中に以下のエラーを出力
```
Unity Package Manager Error
Failed to resolve packages: The file [D:\unity test_ChatGPT-API-unity Packages¥manifest.json] is not valid JSON:
Unexpected token "{" (0x7B) in JSON at position 1820 while parsing near "...xr": "1.0.0\"\n \n}\n\n\n "dependencies\": ...". No packages loaded.
A re-import of the project may be required to fix the issue or a manual modification of D:/unity/test_ChatGPT-API-unity/Packages/manifest.json file.
Click on Retry to relaunch Unity and reopen your project.
Click on Continue to launch Unity. Some or all packages may not be imported which may cause compilation errors.
```
---
以上です。
こちら問題の特定は可能でしょうか。
![名称未設定 2](https://user-images.githubusercontent.com/51348259/223313652-f98a2603-4cdd-426d-8a50-dd7397643909.png)
![名称未設定 3](https://user-images.githubusercontent.com/51348259/223313702-7cb592da-2d7b-4b4a-9a57-d9be77c08950.png)

**Comment by fumitakayano** [comment]
こちらjsonファイルの記述が間違っていました。
![image](https://user-images.githubusercontent.com/51348259/223315445-2aba2f40-24c3-4c00-8301-3786109baa5c.png)
修正したところ無事にインポートできました。

**Comment by mochi-neko** [comment]
触っていただきありがとうございます！
説明がわかりづらくて申し訳ありません！
その対応で問題ありません！
