### ISSUE TITLE
The type or namespace name 'Memory' does not exist in the namespace 'Mochineko.ChatGPT_AP

### ISSUE THREAD

**Issue by sassa4771** [mochi-neko/ChatGPT-API-unity#2]
とても便利なものを公開していただきありがとうございます。
UnityPackageManagerでのimportでMemoryがないとのエラーが発生したので、報告させていただきます。

Readmeを参考にUnityPackageManagerにimportして、
「ChatCompletionSample」サンプルをScriptsに作成したところ

「The type or namespace name 'Memories' does not exist in the namespace 'Mochineko.ChatGPT_API'」
というエラーが発生しました。

Download ZipでダウンロードしたものをUnityで開いた場合は、エラーがなく無事に使用することができました。

また、Zipでダウンロードした「ChatCompletionSample」スクリプトにはMemoriesではなくMemoryが使用されていたため、
MemoriesからMemoryに変更した場合でもMochineko.ChatGPT_APIにはないと表示されました。

お手数ですが、お力をお貸しいただけないでしょうか？

Unity Version：2021.3.0f1
PC：MacBook Pro M1

**Comment by mochi-neko** [comment]
@sassa4771 

報告ありがとうございます！

Readmeが少し古いままのようで、申し訳ありません。

サンプルで使用している `FiniteQueueChatMemory` というクラスが別のMemoryのPackageに分かれているため、この依存関係が不足していてコンパイルエラーが出ている状態だと思われます。

下記の3つ（1番目はReadmeに書いているもの）を `manifest.json` に追加してみて解消されるか確認していただけますでしょうか？

```json
{
  "dependencies": {
    "com.mochineko.chatgpt-api": "https://github.com/mochi-neko/ChatGPT-API-unity.git?path=/Assets/Mochineko/ChatGPT_API#0.4.0",
    "com.mochineko.chatgpt-api.memory": "https://github.com/mochi-neko/ChatGPT-API-unity.git?path=/Assets/Mochineko/ChatGPT_API.Memory#0.4.0",
    "com.mochineko.tiktoken-sharp": "https://github.com/mochi-neko/ChatGPT-API-unity.git?path=/Assets/Mochineko/TiktokenSharp#0.4.0"
  }
}
```

依存関係を気にしすぎて細かくPackageを切りすぎているのが根本的な原因ではありますので、
近いうちにこれらを1つのPackageに整理して改善しようと思います。

**Comment by mochi-neko** [comment]
こちらv0.5.0にてパッケージを一つにまとめましたので、少し簡単に使用できるようになったかと思います。
