### ISSUE TITLE
Enquiry on the use of memory

### ISSUE THREAD

**Issue by enigmablue** [mochi-neko/ChatGPT-API-unity#3]
Hi there i'm trying to find ways to maintain conversation history and also managing context.
I see there is some method to handle chatmemory but i'm not sure what is the context and purpose. Could you help elaborate?

More specifically i'm trying to find out how conversations / prompts can be linked

**Comment by mochi-neko** [comment]
@enigmablue 

Thank you for your enquiry.

Conversation history is a list of [Message](https://github.com/mochi-neko/ChatGPT-API-unity/blob/main/Assets/Mochineko/ChatGPT_API/Message.cs) according to the [API reference](https://github.com/mochi-neko/ChatGPT-API-unity/blob/main/Assets/Mochineko/ChatGPT_API/Message.cs).

Message has the "role" label.
- "system" is an order to LLM.
- "user" is an user input message.
- "assistant" is a LLM output message.

Therefore, "system" is prompt and others are conversation history between human and AI.

You can specify message list by [IChatMemory](https://github.com/mochi-neko/ChatGPT-API-unity/blob/main/Assets/Mochineko/ChatGPT_API/IChatMemory.cs) to set constructor of [ChatCompletionAPIConnection](https://github.com/mochi-neko/ChatGPT-API-unity/blob/main/Assets/Mochineko/ChatGPT_API/ChatCompletionAPIConnection.cs).

ChatCompletionAPIConnection automatically records requests and responses to memory.

Sample implementations of `IChatMemory` are followings:
- [SimpleChatMemory](https://github.com/mochi-neko/ChatGPT-API-unity/blob/main/Assets/Mochineko/ChatGPT_API/SimpleChatMemory.cs)
  - Simple list of messages.
- [FiniteQueueChatMemory](https://github.com/mochi-neko/ChatGPT-API-unity/blob/main/Assets/Mochineko/ChatGPT_API/Memory/FiniteQueueChatMemory.cs)
  - Finite count queue of messages.
- [FiniteTokenLengthQueueChatMemory](https://github.com/mochi-neko/ChatGPT-API-unity/blob/main/Assets/Mochineko/ChatGPT_API/Memory/FiniteTokenLengthQueueChatMemory.cs)
  - Finite total token length list of messages.
- [LongTermChatMemory](https://github.com/mochi-neko/llm-agent-sandbox-unity/blob/main/Assets/Mochineko/LLMAgent/Memory/LongTermChatMemory.cs)
  - Summarize old messages by ChatGPT.

Also you can customize memory logic by implementing [IChatMemory](https://github.com/mochi-neko/ChatGPT-API-unity/blob/main/Assets/Mochineko/ChatGPT_API/IChatMemory.cs).

I hope this will help.

**Comment by enigmablue** [comment]
Thank you but may i ask a stupid question, what is the intention and benefit of setting up memory?

**Comment by mochi-neko** [comment]
I intend to be able to extend memory implementation because needed memory specification depends on use cases.

As an example, ChatGPT API has the limit of token length at one request.

- gpt3.5-turbo: 4096 tokens
  - https://platform.openai.com/docs/models/gpt-3-5 
- gpt4: 8192 or 32768 tokens
  - https://platform.openai.com/docs/models/gpt-4

Token length for these models are calculated by [tiktoken](https://github.com/openai/tiktoken).

Then sometimes it is better to take care of token length in memory e.g. FiniteQueueChatMemory and FiniteTokenLengthQueueChatMemory.

See also [LangChain.Memory](https://python.langchain.com/en/latest/modules/memory.html).

In other cases, if you want to utilize the context of the conversation to request a task to ChatGPT but do not need to record a response, customizing the memory has benefit.

**Comment by enigmablue** [comment]
thank you for your tips!

**Comment by enigmablue** [comment]
May i ask a bit more about this, do you know a way to maximize the token handling so that costs are managed?

For example in a regular ChatGPT conversation, it knows the history of the conversations and it appears to include it in the prompt without us having to manage it. I believe they are handling this as a part of the reinforcement learning mechanism in the web app.

Do you have any idea how that is done or it can be implemented here or in Unity? 

Maybe i dont fully understand your statement: "if you want to utilize the context of the conversation to request a task to ChatGPT but do not need to record a response, customizing the memory has benefit."

Can benefits of langchain also be implemented here?

Thank you so much
