### ISSUE TITLE
CompleteChatAsStreamAsync example

### ISSUE THREAD

**Issue by SeanBannister** [mochi-neko/ChatGPT-API-unity#6]
Thanks for this project, as someone new to C# I would love an example of using CompleteChatAsStreamAsync. I totally appreciate that this might not be a priority but I'm sure it'd help other people looking into this project.

I've been running into problems returning the results and can't quite seem to get it working.

**Comment by mochi-neko** [comment]
Thank you for your request.

OK, I am going to support stream option by `IAsyncEnumerable` and add an example code.

Please wait a moment.

**Comment by SeanBannister** [comment]
That would be awesome thanks so much.

**Comment by mochi-neko** [comment]
I added streaming API support as `IAsyncEnumerable` by ver0.7.0.

You can take chunk (= delta of completion result) by `await foreach`.

Please check [streaming sample code](https://github.com/mochi-neko/ChatGPT-API-unity/blob/main/Assets/Mochineko/ChatGPT_API.Samples/ChatCompletionAsStreamSample.cs).

**Comment by SeanBannister** [comment]
This is awesome, thank you so much.
